### ISSUE TITLE
This repo should probably be renamed

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/asyncapi-react#263]
## Description

Not a problem right now but it's weird that the URL is github.com/asyncapi/asyncapi-react. We can probably rename this to `react` instead so the URL becomes github.com/asyncapi/react. Or maybe we look a bit further and rename it to `ui` as it will become our UI library soon. Also, this repo doesn't only produce React anymore.

**Comment by magicmatatjahu** [comment]
I like `ui` name :) We can also use newest [`exports`](https://nodejs.org/api/packages.html#packages_package_entry_points) field in package.json and make something like:
- `import ... from "@asyncapi/ui/react`
- `import ... from "@asyncapi/ui/components` <- our components library
- `import ... from "@asyncapi/ui/themes` <- defined themes
- `import ... from "@asyncapi/ui/web-component`
- etc.

**Comment by derberg** [comment]
I think best would be to do it with 1.0 release, so users would bump and rename dependency at the same time

**Comment by derberg** [comment]
@magicmatatjahu ping, so you remember about it when releasing 1.0, maybe it should be part of the milestone?

**Comment by magicmatatjahu** [comment]
@derberg Heh, sorry 😅  I missed this comment in notifications. I think that we should postpone that renaming to `2.0.0` and the reason is simple. We don't have our design system (with components) and we already started discussion about it https://github.com/asyncapi/brand/issues/22. So I think that we should create separate repo only for components and design system and then in `2.0.0` move react component to the new repo or maybe second option: create new branch in this repo and there create everything from scratch based on this new design system. In this second option we will preserve Github Stars but we should discuss it.

**Comment by fmvilas** [comment]
Keep it open, dear bot.
