### ISSUE TITLE
does it make sense to maintain our own component for rendering JSON Schema?

### ISSUE THREAD

**Issue by derberg** [asyncapi/asyncapi-react#279]
**Description**

I just created this issue https://github.com/asyncapi/asyncapi-react/issues/278. And I bet we do not cover more cases.
When this component was founded, there was nothing out there that we could reuse. Now I bumped into https://www.npmjs.com/package/@stoplight/json-schema-viewer that looks interesting. 

Maybe we should consider using a component from stoplight (not sure how open they are and how we can drive things with them forward) or actually pulling our schema outside as a separate project to build a community around 🤷🏼 

**Reasons**

I mean who likes to create things that others created already 😄 Just don't waste effort where it is not needed

**Comment by magicmatatjahu** [comment]
@derberg Hi! At the moment JSON Viewer in component is rewritten (https://github.com/asyncapi/shape-up-process/issues/83) to look and have the same capabilities as JSON Viewer in html-template. For example, schema in #278 issue (schema is cutted with `$ref` components) we render (in [unify-component](https://github.com/asyncapi/asyncapi-react/tree/unify-component) branch) as:

![image](https://user-images.githubusercontent.com/20404945/112625287-fda4ae00-8e2e-11eb-815f-bb8c2a85762e.png)

Of course, we have still some problems that `additionaProperties` are rendered before `oneOf` schemas, but as you can see, we "fix" problem from #278 issue.

Using a separate component for schema rendering is not bad, but as I see in code and in examples of mentioned package, it doesn't support:
- union types like `type: ['string', 'number']` - maybe it supports it, but as I wrote I only check examples and some code
- `if`, `then`, `else` schemas - we also don't support it, but I have idea how to handle it 😄 
- I don't sure if component supports `not` schemas
- in description they write that component supports 04 draft of JSON Schema, but what with draft 5, 6, 7, 2019 and 2020-12? 😅 
- what about `discriminator` from our schema - our `schema` object is a full subset of original json schema, but with additional properties like `discriminator` to support inheritance and also `externalDocs`

Next problem is using `lodash` inside package - tbh I'm not big fan of using lodash in front-app, because we must keep the component as small as possible.

Maybe if we write plugins system like in SwaggerUI, then people will be able to "switch" to another JSON Viewer, but in this cycle I don't think that we will have much time for that.
Generally, one of the cycle requirements is that a React component should resemble an html-template :)

**Comment by magicmatatjahu** [comment]
> Maybe we should consider using a component from stoplight (not sure how open they are and how we can drive things with them forward) or actually pulling our schema outside as a separate project to build a community around 🤷🏼

I like this idea to create "separate" package only for out custom JSON Viewer, but maybe in next cycles - as I wrote in previous comment, I have idea how to handle `if`, `then`, `else` etc advanced json schema props.

**Comment by derberg** [comment]
afaik OAS 3.1 fully supports JSON Schema.

my issue has nothing to do with cycle 😛 

the point is that JSON Schema is complex, so the component that renders it, and simply there is no point to duplicate efforts in the community if there are already some other initiatives, especially active ones like the one from stoplight (the are already in advanced 4.0 beta release)

compare it to for example our AsyncAPI Parser. We evolve it and maintain and then somebody else creates theirs as they do not like our parser because it is using AJV and then do not like it. Right? instead of discussing first, exchanging thoughts. And "missing features" is really irrelevant in such a case, as we are also missing many features. It is just better to work on such complex topics in a larger group/community than trying to address everything alone.

you know that loadash dependency is easy to drop or optimize if there are just 2 or 3 functions used 😉 

but yeah, as I said, in my opinion we need to optimize work here, either join them or extract ours.

**Comment by magicmatatjahu** [comment]
@derberg I understand :) We can think about it after unification.

**Comment by Fox32** [comment]
I made some experience with the new v4 beta versions of @stoplight/json-schema-viewer. While the project looks promising, it is very hard to integrate into an existing app with own theming. It's in an early state, I also noticed that some packages aren't public yet (but available under an OSS license on npm). The pull in a lot of additional dependencies.

Right now I'm tempted to check whether the JSON schema component in this repo could be exported for external use 😉

**Comment by derberg** [comment]
> Right now I'm tempted to check whether the JSON schema component in this repo could be exported for external use

@Fox32 this makes sense too, if we evaluate and end up thinking it is better to separate json schema component and build community around it, we should do it. It is either this was or joining the other project

**Comment by magicmatatjahu** [comment]
@Fox32 Hi! Currently we published the "new" component under the `next` branch https://github.com/asyncapi/asyncapi-react/tree/next and Schema component has more options (supports everything from draft-07 except true/false schemas and dependencies) but unfortunately uses our parser API ... We should go with plain properties in it, not use parser functions.

**Comment by derberg** [comment]
looks like getting rid of our json schema component doesn't make sense now as we already have it pretty good. Idea to have the component separated and be more generic is also something that is not important for now and we won't have time to really work on it in next months. Thus closing

**Comment by magicmatatjahu** [comment]
@derberg I think that we should create another one issue, related only to the standalone JSON Schema component.  In a long term we need this component for problems/features such a https://github.com/asyncapi/extensions-catalog/issues/43

**Comment by derberg** [comment]
yeah, but it is future like future future, so creating issue now will only feed the stale bot 😄

**Comment by magicmatatjahu** [comment]
Separate issue -> https://github.com/asyncapi/asyncapi-react/issues/426

> yeah, but it is future like future future, so creating issue now will only feed the stale bot 😄

But then you won't forget it 😄

**Comment by derberg** [comment]
🤷🏼
