### ISSUE TITLE
Question - Status standalone-bundle

### ISSUE THREAD

**Issue by thim81** [asyncapi/asyncapi-react#524]
**Description**

I have been looking at the nicely looking standalone version of the AsyncAPI bundle
https://github.com/asyncapi/asyncapi-react/blob/next/docs/usage/standalone-bundle.md#usage-in-html-webpage

I'm looking for the split view mode, where you have the properties left & right the payload examples.
Which looks very very good with the standalone-bundle setup.

I'm confused with the documentation, if this will be still supported in the future and if I'm using the latest version of it?
I took the sample as described: https://github.com/asyncapi/asyncapi-react/blob/next/docs/usage/standalone-bundle.md#usage-in-html-webpage

**Comment by thim81** [comment]
For example, I noticed that the Bundled version does not support `asyncapi: 2.2.0`

![2022-01-18 at 17 11 57](https://user-images.githubusercontent.com/952446/149974956-4344588a-2021-47cd-ba30-dfcc6ed0a9b6.png)

**Comment by magicmatatjahu** [comment]
@thim81 Hello! Standalone bundle only exists for the `next` version of component which we want (with hope) to merge very soon, and yes if it will be merged to the `master` it will be still available, we don't want to remove that bundle, because user should have possibility to use that component in other libs/frameworks than React.

> I'm using the latest version of it?

If you want use latest version you should use latest version from `releases` section -> https://github.com/asyncapi/asyncapi-react/releases Atm it is `next.31` so link should be:

```
https://unpkg.com/@asyncapi/react-component@1.0.0-next.31/browser/standalone/index.js
```

Have in mind to update also link to the styles :)

> For example, I noticed that the Bundled version does not support asyncapi: 2.2.0

You probably use old version, `2.2.0` is added in `next-19` release https://github.com/asyncapi/asyncapi-react/releases/tag/v1.0.0-next.19

Do you want to know more?

**Comment by thim81** [comment]
@magicmatatjahu Thanks for taking the time to give me all the answers to my questions.

I was confused about the bundled app, but now it is clear that is part of the `asyncapi-react` package.
I landed on the https://github.com/asyncapi/asyncapi-react/blob/next/docs/usage/standalone-bundle.md#usage-in-html-webpage but there was nothing from the "bundle" in the readme, so I was a bit lost.

I'll update my application to the use the latest version and figure out how keep track of the changes.

**Comment by magicmatatjahu** [comment]
@thim81 Good to hear! We have docs for using that standalone bundle in the [Angular2+](https://github.com/asyncapi/asyncapi-react/blob/next/docs/usage/angular.md#standalone-bundle) and also in the [Vue](https://github.com/asyncapi/asyncapi-react/blob/next/docs/usage/vue.md). If are you using that bundle in another lib/framework please let us know and we can create another doc :)

**Comment by thim81** [comment]
I'm using it in a plain HTML, which works perfect for me. 

I cannot thank you enough for the great work you are doing in making AsyncAPI looks so great! 🙌

**Comment by magicmatatjahu** [comment]
@thim81 Thanks! ❤️  If you have any other questions, please feel free to ask :)
