### ISSUE TITLE
Misplaced/improperly rendered Example section when using wider screens

### ISSUE THREAD

**Issue by xBlaz3kx** [asyncapi/asyncapi-react#542]
#### Describe the bug

Misplaced **Example** section of the docs. Probably has something to do with CSS file and how it is generated, since resizing the browser window put it in it's designated place. 

#### How to Reproduce

Generated the site with Docker using `-o /app/output /app/asyncapi.yaml @asyncapi/html-template --force-write` and deployed with Nginx. Tried with version 2.0.0. and 2.2.0 of the AsyncAPI spec, both showed the same result. Accessed the website with Chrome and Firefox, both had the same result (picture attached below, details of the page are crossed out because of the work related stuff). Tried it on both ultrawide 34" and 27" monitors, both are 1440p.

![image](https://user-images.githubusercontent.com/22869613/152254663-e80ddc5a-9253-4eff-b18e-a47ef190df23.png)

#### Expected behavior

The example section should be placed under the message description regardless of the browser or the screen.

**Comment by magicmatatjahu** [comment]
@xBlaz3kx Hi!

> The example section should be placed under the message description regardless of the browser or the screen.

No, in some screen resolution (above 1024px width) examples should render on the right. They render in that place from 1 year and no one has had a problem until now 😅  As you yourself noticed when you reduce the resolution then the examples are under the message. We don't plan to change this. Also, we are not alone with that solution because there is a similar approach in other rendering tools another spec like OpenAPI, e.g. Redoc, and overall people like it. Here you have an example https://redocly.github.io/redoc/. Do you wanna add something? Also remember Message examples =/= Schema examples

**Comment by xBlaz3kx** [comment]
@magicmatatjahu Thanks for the clarification. I was basing this on what I saw in the AsyncAPI Studio, where it rendered under the payload structure, so it seemed a bit odd to render on the side. I'm not sure if I like it or not, because there's no clear indicator on whether it is supposed to be there or not.

**Comment by magicmatatjahu** [comment]
@xBlaz3kx If you resize editor panel you can see that "wider" version of component on the right, example:

![image](https://user-images.githubusercontent.com/20404945/152322240-e8cfa763-59a1-4ddd-a802-def3aa5b1384.png)

> I'm not sure if I like it or not, because there's no clear indicator on whether it is supposed to be there or not.

I know someone may not like it, but it's a UX topic, it's not math that 1+1 should give you 2, it just depends on people's preferences. The only indicator of position changes is the width in which the components are rendered. If it is greater than 1024 (or 1280, sorry I can't remember) then you have that version wider. If we rendered everything underneath each other then on 2k monitors (like I have) it wouldn't look good because everything would be very stretched.

Do you wanna add something more? If not, I will close issue :)

Btw. we have such a https://github.com/asyncapi/asyncapi-react/issues/464 feature proposal to hide/show that right panel by button, you should be interest. There is a live mock in figma https://www.figma.com/proto/HSOI1LQerObYAcIK5Qmw0j/Studio-Docs---Examples-Sidebar?page-id=2%3A2&node-id=3%3A64&viewport=241%2C48%2C0.25&scaling=scale-down&starting-point-node-id=3%3A64&show-proto-sidebar=1

**Comment by xBlaz3kx** [comment]
@magicmatatjahu Yeah I understand its a UX debate, just thought this wasn't intended. Also I didn't notice you could stretch the window in AsyncAPI Studio. 

The feature proposal looks great, would definitely be an improvement. While we're at the topic of UX, is dark mode planned?

**Comment by magicmatatjahu** [comment]
@xBlaz3kx Sorry I didn't notice that comment. 

> While we're at the topic of UX, is dark mode planned?

Yeah, we have such a plan, but I don't know when we'll finally do it, I have other tasks on my mind.

I'm closing this issue. If needed please comment or create a new one. Cheers!
