### ISSUE TITLE
Declare react as dependency

### ISSUE THREAD

**Issue by gabormagyar** [asyncapi/asyncapi-react#609]
As reported by yarn pnp:

```
➜  yarn ag build/asyncapi.yml @asyncapi/html-template -o ./docs --force-write
Something went wrong:
Error: @asyncapi/react-component tried to access react, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
```

**Comment by magicmatatjahu** [comment]
@gabormagyar Hi! Thanks for issue! It is a good practice not to define `react` in libraries with a specific version, because some people can use version 16 and others can use version 17 and thus the version is chosen and used on the project side and not on the library side. As far as I can see it is a bug related to yarn itself not to our package. Could you try with fix like [here](https://github.com/styled-components/styled-components/issues/3082)?

**Comment by merceyz** [comment]
> As far as I can see it is a bug related to yarn itself not to our package

@magicmatatjahu It's not an issue with Yarn, in this case `@asyncapi/react-component` should declare `react` as a peer dependency.
https://yarnpkg.com/advanced/rulebook#packages-should-only-ever-require-what-they-formally-list-in-their-dependencies

**Comment by magicmatatjahu** [comment]
@merceyz Yeah right 🤦🏼 I forgot about `peers`. Thanks!

**Comment by magicmatatjahu** [comment]
Resolved by https://github.com/asyncapi/asyncapi-react/pull/614
