### ISSUE TITLE
CSP violation in AsyncApi React component

### ISSUE THREAD

**Issue by ShelMatt** [asyncapi/asyncapi-react#741]
**Description**
I'm trying to use AsyncApiComponent in React to display the AsyncAPI documentation in a web page. But I'm getting an error which says **Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'unsafe-inline'".** in the console. I tried to troubleshoot the issue. I found somewhere in ajv the code is calling a new Function.

**Expected result**
The AsyncAPI should be displayed.

**Actual result**
**Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'unsafe-inline'".**

**Steps to reproduce**

![image](https://github.com/asyncapi/asyncapi-react/assets/140058160/03b4711e-afbd-4d32-b3dc-1080227f95af)

**Troubleshooting**
I tried to understand the base of this issue.  I found somewhere in ajv the code is calling a new Function.
**try {
      var makeValidate = new Function(
        'self',
        'RULES',
        'formats',
        'root',
        'refVal',
        'defaults',
        'customRules',
        'equal',
        'ucs2length',
        'ValidationError',
        sourceCode
      );**

**Comment by AceTheCreator** [comment]
@ShelMatt do you mind showing I can reproduce this error?

**Comment by sevdog** [comment]
To reproduce the error just serve the browser standalone behind a reverse proxy which defines a [CSP](https://content-security-policy.com/) which does includes `unsafe-eval` (because the constructor of `Function`, which was highlighted by the opener, is considered as that).

The issue is within ajv (which is a inherithed dependency from [@asyncapi/openapi-schema-parse](https://github.com/asyncapi/openapi-schema-parser/blob/61d9b9fdd05946cafabd4a3001f8635021fe19d1/package.json#L54)):

https://github.com/ajv-validator/ajv/blob/f177fe323420ccb23e1a79445fd470cbf80aee7c/lib/compile/jtd/parse.ts#L69


See also: https://github.com/ajv-validator/ajv/issues/2527
