### ISSUE TITLE
Black right panel for "examples" fills 1/3 of the screen without useful content (just black background)

### ISSUE THREAD

**Issue by ValeryShvyndzikau** [asyncapi/asyncapi-react#954]
Hi AsyncAPI team,
Is it possible to configure html output to keep "examples" below the message sections, like it's rendered within the AsyncAPI editor, or SwaggerHub editor?
![image](https://github.com/asyncapi/html-template/assets/1850133/6766cef9-7011-4b78-b747-7372058b1df0)

SwaggerHub example
![image](https://github.com/asyncapi/html-template/assets/1850133/0531ee46-b7f7-4391-b859-07bcd69ac5fc)

AsyncAPi editor example
![image](https://github.com/asyncapi/html-template/assets/1850133/4dc20af5-7264-48b4-a432-a405e824ef68)

It looks almost similar when I decreased browser window width, but is it possible to configure it as part of output html generation?
![image](https://github.com/asyncapi/html-template/assets/1850133/5b7b7ac8-c3b4-4bc2-afe6-e4db5c09ddeb)

**Comment by derberg** [comment]
@ValeryShvyndzikau thanks, moved it here as HTML-template is just a wrapper around this component to enable people generate with AsyncAPI Generator

@AMulgrave autogeneration of examples is a separate topic, so I suggest you submit a separate issue for it. Atm, you can disable autogeneration by providing own custom examples. Anyway, please open separate issue, even if it is maybe just a question about how things work.

**Comment by aditygrg2** [comment]
@ValeryShvyndzikau @AceTheCreator I personally feel good to have examples and the parameters side-by-side, but I agree that this takes a lot of space too. 

I would suggest either resizing the example column, or just collapsing it completely by adding an arrow at the top right. This will stop enforcing the lot of width the side of examples is taking. 

For smaller screens, it is already fine as the examples will appear below the requests only.

**Comment by catosaurusrex2003** [comment]
There are 2 fixes for this
1. Remove the right panel all together 
   - this might have side-effects because a lot of css must be altered for this
   - might cause problem if we need the right panel again in future if it serves more purposes than showing examples in bigger  screens.
2. Increase the breaking point in px so that the examples dont come in right panel for normal desktop screens
   - this is simple one word fix and wont have side effects

i think the 2nd options is better to move forward with.
